# This is a basic workflow to help you get started with Actions

name: UpdateVitals

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #
      #Repo Name
#       - name: Run a one-line script
#         run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sed -i 's/vitals-testing/${{ github.event.repository.name }}/g' vitals.yaml
          git config --global user.email "pradeep@pradeep.com"
          git config --global user.name "Your Name"
          git commit -am "Automated report"
          git push 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       - name: commit and push
#         uses: ad-m/github-push-action@master
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #    BRANCH_NAME: 'main'
# Runs a single command using the runners shell                

          
          

